### ISSUE TITLE
Why does it need "WRITE_EXTERNAL_STORAGE" ? 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ZahraHeydari/MusicPlayer#2]
A music player is supposed to only read...

**Comment by ZahraHeydari** [comment]
Yes, the player doesn`t need the permission but this permission is used for another part of the code when we want to select a song from device and store it in database.

**Comment by AndroidDeveloperLB** [comment]
What part of the code does it need to write to some path of the device?
For what purpose?

**Comment by ZahraHeydari** [comment]
I`ve explained the scenario of this sample code how to use the player for playing songs from stored playlist but maybe need to add a gif or some photos of how it works.

**Comment by AndroidDeveloperLB** [comment]
You mean this:
"To add songs from the device, save them in database and display them in a list. And when a list item is clicked, the app displays a player page and a player service run. (This player also supports all actions on played song.) And if you click long on the song item you will be able to remove it from your stored playlist.
"
?
It doesn't explain (and doesn't even mention) about storage at all. Why would it put any file outside of the app?
Does it save the playlist or the DB outside of the app?

**Comment by ZahraHeydari** [comment]
It is just a scenario to show how to use the player. I have not  create the player as module yet. So it is a little confusing but I am working on it and as soon as it is ready I definitely will add a better documentation.

**Comment by AndroidDeveloperLB** [comment]
I actually don't get the purpose of this project. Is it a sample of using various SDKs of the newest versions?
Is it a real app that will be published? Is it supposed to be used by other apps?
It's not looking like a music player (yet) ...

**Comment by ZahraHeydari** [comment]
This is only a sample app and I`m gonna separate the player package and create it as module to use it as a feature in any android application but it still has lots of things to be fixed and improved. So you can consider this project as a sample code at the moment.

**Comment by AndroidDeveloperLB** [comment]
OK but you didn't explain why you need to write to storage, and given that Google is restricting the storage API more and more, I don't think it's wise to use it to create a special file somewhere. I think only media files are ok for this.

**Comment by ZahraHeydari** [comment]
Thanks for mentioning this issue. I was not paying attention to "Write" key. Definitely there is no need to use "WRITE_EXTERNAL_STORAGE" permission in this case. I changed it to "READ_EXTERNAL_STORAGE".

**Comment by AndroidDeveloperLB** [comment]
But... I explained it in the beginning...

**Comment by ZahraHeydari** [comment]
I know. I just explained the scenario of this sample code.
