### ISSUE TITLE
Bug: app crashes right when starting to play in background

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ZahraHeydari/MusicPlayer#3]
See attached video:

[2019-12-01_22-51-17.zip](https://github.com/ZahraHeydari/MusicPlayer/files/3908699/2019-12-01_22-51-17.zip)

You need to add:

```
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
```

But even then, when I try to start playing, it doesn't do anything:

[2019-12-01_22-53-27.zip](https://github.com/ZahraHeydari/MusicPlayer/files/3908702/2019-12-01_22-53-27.zip)

**Comment by ZahraHeydari** [comment]
Apps targeting Android Q (API 29) by default are given a filtered view into external storage. I solved this issue by adding:
`<manifest ... >
    <application android:requestLegacyExternalStorage="true" ... >
     ...
    </application>
</manifest>
`

**Comment by AndroidDeveloperLB** [comment]
This isn't a proper solution, especially in a repository.
It's a temporary one

**Comment by AndroidDeveloperLB** [comment]
Just a note: I don't like what Google is doing with the storage. It even made weirder claims and decisions on a recent video :

https://www.youtube.com/watch?v=UnJ3amzJM94&feature=youtu.be&t=369

**Comment by ZahraHeydari** [comment]
Thanks for sharing.

**Comment by AndroidDeveloperLB** [comment]
Yes, there is a lot of talk against it on reddit, and there are multiple articles about it by CommonsWare.

I have no idea what will happen, and I'm very confused by the huge amount of information that exists about it.
