### ISSUE TITLE
Can't run MusicPlayer

### ISSUE THREAD

**Issue by a1573595** [ZahraHeydari/MusicPlayer#6]
Hi, I encountered the following error when executing the project

D:\Android\MusicPlayer\app\build\tmp\kapt3\stubs\debug\com\android\musicplayer\data\model\Song.java:8: error: Multiple fields have the same columnName: duration. Field names: duration, duration.
public final class Song extends com.android.player.model.ASong implements android.os.Parcelable {
             ^

After trying several methods are still unable to run the project order:
1. Delete .idea file and restart Project.
2. Build → Clean project → Rebuild Project.
3. Build → Clean project → Make Project.

Did I miss something?

**Comment by ZahraHeydari** [comment]
May I know, this error happened on which android version? Although, I fixed some issues and I will update my source code soon.

**Comment by ZahraHeydari** [comment]
I fixed this bug by adding @Transient annotation before local fields of ASong class. I also solved some other issues and updated my source code. Now you can use it and it would be great if you let me know if this issue still exists!

**Comment by ZahraHeydari** [comment]
I fixed this bug by adding @Transient annotation before local fields of ASong class. I also solved some other issues and updated my source code. Now you can use it and it would be great if you let me know if this issue still exists!

**Comment by ZahraHeydari** [comment]
I fixed this bug by adding ~@Transient~ annotation before local fields of ASong class. I also solved some other issues and updated my source code. Now you can use it and it would be great if you let me know if this issue still exists!

**Comment by ZahraHeydari** [comment]
I fixed this bug by adding **Transient** annotation before local fields of **ASong** class. I also solved some other issues and updated my source code. Now you can use it and it would be great if you let me know if this issue still exists!

**Comment by a1573595** [comment]
Thanks.
